### ISSUE TITLE
/roll conflicts with Roll Monitor from Kapture

### ISSUE THREAD

**Issue by Grammernatzi** [53m1k0l0n/FFXIV-LazyLoot#17]
That is all. As a result, whichever loads last has command priority and blocks the other.

**Comment by 53m1k0l0n** [comment]
Oh shit yeah, totally forgotten.

**Comment by Grammernatzi** [comment]
No problem, just wanted to mention it. I had issues with the new command on some loads and not on others, and then I noticed my macros were popping up the roll monitor when it wasn't working and it made sense. Figured to let you know.

**Comment by 53m1k0l0n** [comment]
Yeah thanks for telling will change it when i'm back home again.
