### ISSUE TITLE
[Feature request] Roll delay

### ISSUE THREAD

**Issue by SmoothJaz** [53m1k0l0n/FFXIV-LazyLoot#2]
is it possible to have an option to add a delay (like 1.5-2 seconds) to the needs and greeds so they're not all instant? looks super sus using in alliance raids when there's like upwards of 7 items that all get instantly rolled for by you

**Comment by 53m1k0l0n** [comment]
Should it be configurable?

**Comment by SmoothJaz** [comment]
That would definitely be ideal, but I don't know how much extra work that would end up being

**Comment by 53m1k0l0n** [comment]
I'm gonna test some ideas later.

**Comment by 53m1k0l0n** [comment]
Testing a soulution, if i'm okay with it, there will be a configable delay in the next update.

**Comment by 53m1k0l0n** [comment]
Added with 4.0.0.0.
