### ISSUE TITLE
[Feature] Randomize roll delay

### ISSUE THREAD

**Issue by pistolwhip-dev** [53m1k0l0n/FFXIV-LazyLoot#20]
You introduced the basic configurable roll delays in #2 and this is a request to enhance the feature a bit.

I'd find it useful if we could set a min and max delay, from which the used delay would be randomly chosen between on a per roll basis.  Basically make it a little less robotic.

i.e. 
Min Delay : .5
Max Delay : 1.5

Roll 1 : .75
Roll 2 : 1.2
Roll 3 : .6

and so on

**Comment by 53m1k0l0n** [comment]
I'll think about, but for now i have Paladin stuff on my agenda.

**Comment by 53m1k0l0n** [comment]
I'll do It tomorrow when I'm back home. I think release will be a bit later.
