### ISSUE TITLE
Install fails due to the latest.zip structure

### ISSUE THREAD

**Issue by zbee** [53m1k0l0n/FFXIV-LazyLoot#6]
```
--------------------------------
06:47:24.590 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.ArgumentException: Value must exist (Parameter 'mainAssemblyPath')
   at Dalamud.Plugin.Internal.Loader.LoaderConfig..ctor(String mainAssemblyPath) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\LoaderConfig.cs:line 27
   at Dalamud.Plugin.Internal.Types.LocalPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 154
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 942
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 822
--------------------------------
```

Install fails due to the folder at the root of your release .zip, .dll should be at the root

The folder structure in the .zip your repo directs to does not have the .dll file at the root of the file, instead it is inside of a folder.

For example, my repo https://zbee.codes/xiv-plugins-repo.json works because the file it directs to (https://zbee.codes/plugin-downloads/LL.zip) has the .dll file at the root of the archive.

**Comment by 53m1k0l0n** [comment]
First which repo do you mean exactly and which zip do you mean?

**Comment by 53m1k0l0n** [comment]
If you mean the 5.0.7.zip this is only for manual install all other are lastest.zip and this doesn't have a folder inside.

**Comment by 53m1k0l0n** [comment]
And it could be possible that you got an old repo information, because github has CDN problems.

**Comment by 53m1k0l0n** [comment]
if i look at the raw repo i get this

[
  {
    "Author": "53m1k0l0n",
    "Name": "Lazy Loot",
    "Description": "Various commands to need, greed, or pass on all loot. Chat and Toast output and delay for rolling.",
    "InternalName": "LazyLoot",
    "AssemblyVersion": "5.0.5",
    "Changelog": "Version bump?",
    "RepoUrl": "https://github.com/53m1k0l0n/FFXIV-LazyLoot",
    "ApplicableVersion": "any",
    "Tags": [
      "plugin",
      "loot",
      "utility",
      "other"
    ],
    "DalamudApiLevel": 8,
    "IsHide": "False",
    "IsTestingExclusive": "False",
    "LastUpdated": 0,
    "DownloadCount": 0,
    "IconUrl": "https://raw.githubusercontent.com/53m1k0l0n/FF14_Plugins/main/LazyLoot/images/icon.png",
    "DownloadLinkInstall": "https://github.com/53m1k0l0n/FF14_Plugins/blob/main/LazyLoot/latest.zip?raw=true",
    "DownloadLinkTesting": "https://github.com/53m1k0l0n/FF14_Plugins/blob/main/LazyLoot/latest.zip?raw=true",
    "DownloadLinkUpdate": "https://github.com/53m1k0l0n/FF14_Plugins/blob/main/LazyLoot/latest.zipp?raw=true"
  }
]

which is wrong

because it should be this
[
  {
    "Author": "53m1k0l0n",
    "Name": "Lazy Loot",
    "Description": "Various commands to need, greed, or pass on all loot. Chat and Toast output and delay for rolling.",
    "InternalName": "LazyLoot",
    "AssemblyVersion": "5.0.7",
    "Changelog": "Config save excutes properly now",
    "RepoUrl": "https://github.com/53m1k0l0n/FFXIV-LazyLoot",
    "ApplicableVersion": "any",
    "Tags": [
      "plugin",
      "loot",
      "utility",
      "other"
    ],
    "DalamudApiLevel": 8,
    "IsHide": "False",
    "IsTestingExclusive": "False",
    "LastUpdated": 0,
    "DownloadCount": 0,
    "IconUrl": "https://raw.githubusercontent.com/53m1k0l0n/FFXIV-LazyLoot/main/LazyLoot/Images/icon.png",
    "DownloadLinkInstall": "https://github.com/53m1k0l0n/FFXIV-LazyLoot/releases/download/v5.0.7/latest.zip",
    "DownloadLinkUpdate": "https://github.com/53m1k0l0n/FFXIV-LazyLoot/releases/download/v5.0.7/latest.zip"
  }
]

**Comment by 53m1k0l0n** [comment]
But you are right the latest.zip had an error because it was LMZA and not Deflate.

**Comment by zbee** [comment]
I do see that now, too, but the zip I had pulled that dalamud got was indeed outdated. Just a caching issue, I suppose.
